on: [ pull_request ]

jobs:
  cpp_style_check:
    runs-on: ubuntu-latest
    name: Check C++ Styling
    steps:
    - name: Checkout this commit
      uses: actions/checkout@v3
    - name: uncrustify-check
      uses: Daniel-Trevitz/uncrustify-check@v0.2.0
      with:
        configFile: 'uncrustify.cfg'
